version: '2.3'
volumes:
  archived_data:
  uploaded_data:
  static_data:
  uppy_data:
services:
  cache:
    ports:
      - "127.0.0.1:6379:6379"
    extends:
      file: docker-services.yml
      service: cache
  db:
    ports:
      - "127.0.0.1:5432:5432"
    extends:
      file: docker-services.yml
      service: db
  mq:
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    extends:
      file: docker-services.yml
      service: mq
  es:
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    extends:
      file: docker-services.yml
      service: es7
